config/routes.rb
Rails.application.routes.draw do
  resources :twiconts
  resources :alibis
  resources :tests

  get "/auth/twitter/callback" => "sessions#callback"
  get "/logout" => "sessions#destroy", :as => :logout
  root 'alibis#index'
  post "/add" => "alibis#add"
  post "/make_suggestion" => "sessions#make_suggestion"
  get "/get_alibis" => "alibis#get_alibis"
  get "/delete_alibi" => "alibis#delete_alibi"
  post "/update_alibi" => "alibis#update_alibi"
  post "/add_tweet" => "twiconts#add_tweet"
  get "/get_tweet" => "twiconts#get_tweet"
  get "/delete_tweet" => "twiconts#delete_tweet"
  post "/update_tweet" => "twiconts#update_tweet"

end

app/models/alibi.rb
class Alibi < ActiveRecord::Base
	has_many :twiconts
	has_many :users
end

app/controllers/alibis_controller.rb
class AlibisController < ApplicationController
  before_action :set_alibi, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :add

  # GET /alibis
  # GET /alibis.json
  def index
    @alibis = Alibi.all
  end

  # GET /alibis/1
  # GET /alibis/1.json
  def show
  end

  # GET /alibis/new
  def new
    @alibi = Alibi.new
  end

  # GET /alibis/1/edit
  def edit
  end

  # POST /alibis
  # POST /alibis.json
  def create
    @alibi = Alibi.new(alibi_params)
    respond_to do |format|
      if @alibi.save
        format.html { redirect_to @alibi, notice: 'Alibi was successfully created.' }
        format.json { render :show, status: :created, location: @alibi }
      else
        format.html { render :new }
        format.json { render json: @alibi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alibis/1
  # PATCH/PUT /alibis/1.json
  def update
    respond_to do |format|
      if @alibi.update(alibi_params)
        format.html { redirect_to @alibi, notice: 'Alibi was successfully updated.' }
        format.json { render :show, status: :ok, location: @alibi }
      else
        format.html { render :edit }
        format.json { render json: @alibi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alibis/1
  # DELETE /alibis/1.json
  def destroy
    @alibi.destroy
    respond_to do |format|
      format.html { redirect_to alibis_url, notice: 'Alibi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add
    @alibi = Alibi.create(route_object: params[:route_object],dep_time: params[:departure],user_id: current_user.uid)
    render text: @alibi.id
  end

  def delete_alibi
    Alibi.delete(["id = ?",params[:id]])
    render nothing: true
  end

  def get_alibis
    current_users_alibis = Alibi.where(user_id: current_user.uid)
    render json: current_users_alibis
  end
  def update_alibi
    Alibi.update(params[:id],dep_time: params[:departure], route_object: params[:route_object])
    Twicont.delete_all(["alibi_id = ?",params[:id]])
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alibi
      @alibi = Alibi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alibi_params
      params.require(:alibi).permit(:dep_time, :route_object, :user_id)
    end
end

app/helpers/alibis_helper.rb
module AlibisHelper
end

app/views/alibis/_form.html.erb
<%= form_for(@alibi) do |f| %>
  <% if @alibi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alibi.errors.count, "error") %> prohibited this alibi from being saved:</h2>

      <ul>
      <% @alibi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dep_time %><br>
    <%= f.datetime_select :dep_time %>
  </div>
  <div class="field">
    <%= f.label :route_object %><br>
    <%= f.text_field :route_object %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alibis/_res_text.html.erb
<%= raw time.content%>

app/views/alibis/add.html.erb
<html></html>

app/views/alibis/edit.html.erb
<h1>Editing Alibi</h1>

<%= render 'form' %>

<%= link_to 'Show', @alibi %> |
<%= link_to 'Back', alibis_path %>

app/views/alibis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alibis</h1>

<table>
  <thead>
    <tr>
      <th>dep time</th>
      <th>route object</th>
      <th>user id</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @alibis.each do |alibi| %>
      <tr>
        <td><%= alibi.dep_time %></td>
        <td><%= alibi.route_object %></td>
        <td><%= alibi.user_id %></td>
        <td><%= link_to 'Show', alibi %></td>
        <td><%= link_to 'Edit', edit_alibi_path(alibi) %></td>
        <td><%= link_to 'Destroy', alibi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alibi', new_alibi_path %>

app/views/alibis/new.html.erb
<h1>New Alibi</h1>

<%= render 'form' %>

<%= link_to 'Back', alibis_path %>

app/views/alibis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dep time:</strong>
  <%= @alibi.dep_time %>
</p>

<p>
  <strong>Route object:</strong>
  <%= @alibi.route_object %>
</p>

<p>
  <strong>User:</strong>
  <%= @alibi.user_id %>
</p>

<%= link_to 'Edit', edit_alibi_path(@alibi) %> |
<%= link_to 'Back', alibis_path %>