config/routes.rb
Rails.application.routes.draw do
  resources :twiconts
  resources :alibis
  resources :tests

  get "/auth/twitter/callback" => "sessions#callback"
  get "/logout" => "sessions#destroy", :as => :logout
  root 'alibis#index'
  post "/add" => "alibis#add"
  post "/make_suggestion" => "sessions#make_suggestion"
  get "/get_alibis" => "alibis#get_alibis"
  get "/delete_alibi" => "alibis#delete_alibi"
  post "/update_alibi" => "alibis#update_alibi"
  post "/add_tweet" => "twiconts#add_tweet"
  get "/get_tweet" => "twiconts#get_tweet"
  get "/delete_tweet" => "twiconts#delete_tweet"
  post "/update_tweet" => "twiconts#update_tweet"

end

app/models/twicont.rb
class Twicont < ActiveRecord::Base
	belongs_to :alibis
	belongs_to :users
end

app/controllers/twiconts_controller.rb
class TwicontsController < ApplicationController
	protect_from_forgery except: :add_tweet

	def add_tweet
		@twicont = Twicont.create(twidt: params[:tim],twict: params[:text],twilng: params[:lng],twilat: params[:lat],user_id: current_user.uid,alibi_id:params[:ali],name: params[:name])
		render text: @twicont.id
	end

    def delete_tweet
    	Twicont.delete_all(["id = ?",params[:id]])
    	render nothing: true
    end

	def get_tweet
		@tweet = Twicont.where(alibi_id: params[:id])
		render json: @tweet
	end

	def update_tweet
		Twicont.update(params[:id], twidt: params[:tim], twict: params[:text])
		render nothing: true		
	end
	
end

app/helpers/twiconts_helper.rb
module TwicontsHelper
end

app/views/twiconts/_form.html.erb
<%= form_for(@twicont) do |f| %>
  <% if @twicont.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twicont.errors.count, "error") %> prohibited this twicont from being saved:</h2>

      <ul>
      <% @twicont.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :twidt %><br>
    <%= f.datetime_select :twidt %>
  </div>
  <div class="field">
    <%= f.label :twict %><br>
    <%= f.text_field :twict %>
  </div>
  <div class="field">
    <%= f.label :alibi_id %><br>
    <%= f.number_field :alibi_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twiconts/edit.html.erb
<h1>Editing Twicont</h1>

<%= render 'form' %>

<%= link_to 'Show', @twicont %> |
<%= link_to 'Back', twiconts_path %>

app/views/twiconts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Twiconts</h1>

<table>
  <thead>
    <tr>
      <th>Twidt</th>
      <th>Twict</th>
      <th>Alibi</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twiconts.each do |twicont| %>
      <tr>
        <td><%= twicont.twidt %></td>
        <td><%= twicont.twict %></td>
        <td><%= twicont.alibi_id %></td>
        <td><%= twicont.user_id %></td>
        <td><%= link_to 'Show', twicont %></td>
        <td><%= link_to 'Edit', edit_twicont_path(twicont) %></td>
        <td><%= link_to 'Destroy', twicont, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twicont', new_twicont_path %>

app/views/twiconts/new.html.erb
<h1>New Twicont</h1>

<%= render 'form' %>

<%= link_to 'Back', twiconts_path %>

app/views/twiconts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twidt:</strong>
  <%= @twicont.twidt %>
</p>

<p>
  <strong>Twict:</strong>
  <%= @twicont.twict %>
</p>

<p>
  <strong>Alibi:</strong>
  <%= @twicont.alibi_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @twicont.user_id %>
</p>

<%= link_to 'Edit', edit_twicont_path(@twicont) %> |
<%= link_to 'Back', twiconts_path %>